#!/bin/sh -e
##  by Alexander Wirt <formorer@debian.org>
##
## All lines beginning with `## DP:' are a description of the patch.
## DP: No description

if [ $# -lt 1 ]; then
    echo >&2 "`basename $0`: script expects -patch|-unpatch as argument"
    exit 1
fi

[ -f debian/patches/00patch-opts ] && . debian/patches/00patch-opts
patch_opts="${patch_opts:--f --no-backup-if-mismatch} ${2:+-d $2}"

case "$1" in
       -patch) patch $patch_opts -p0 < $0;;
       -unpatch) patch $patch_opts -p0 -R < $0;;
        *)
                echo >&2 "`basename $0`: script expects -patch|-unpatch as argument"
                exit 1;;
esac

exit 0

@DPATCH@
\n
--- autoconf/linux.in.orig	2004-09-27 21:21:41.000000000 +0200
+++ autoconf/linux.in	2004-09-27 21:21:55.000000000 +0200
@@ -1,7 +1,7 @@
-CHKCONF = /sbin/chkconfig
-CHKCONFIG = /sbin/chkconfig --add dansguardian
-CHKCONFIGDEL = /sbin/chkconfig --del dansguardian
-DEB_RC = /usr/sbin/update-rc.d
+#CHKCONF = /sbin/chkconfig
+#CHKCONFIG = /sbin/chkconfig --add dansguardian
+#CHKCONFIGDEL = /sbin/chkconfig --del dansguardian
+#DEB_RC = /usr/sbin/update-rc.d
 
 
 ################################################################
@@ -85,12 +85,12 @@
 	cp -f ./dansguardian.pl $I$(CGIBINLOCATION)dansguardian.pl
 	chmod o+x $I$(CGIBINLOCATION)dansguardian.pl
 	cp -f ./dansguardian.8.gz $I$(MANUALFILES)man8/dansguardian.8.gz
-	chown -R $(PROXYUSER):$(PROXYGROUP) $I$(LOGLOCATION)
-	chmod -R u+wr $I$(LOGLOCATION)
-	chmod -R og-w $I$(LOGLOCATION)
-	chmod u+wrx $I$(LOGLOCATION)
-	if [ -f $(CHKCONF) ]; then $(CHKCONFIG); fi
-	if [ -f $(DEB_RC) ]; then $(DEB_RC) dansguardian defaults 50; fi
+#	chown -R $(PROXYUSER):$(PROXYGROUP) $I$(LOGLOCATION)
+#	chmod -R u+wr $I$(LOGLOCATION)
+#	chmod -R og-w $I$(LOGLOCATION)
+#	chmod u+wrx $I$(LOGLOCATION)
+#	if [ -f $(CHKCONF) ]; then $(CHKCONFIG); fi
+#	if [ -f $(DEB_RC) ]; then $(DEB_RC) dansguardian defaults 50; fi
 	if [ -d $(LOGROTATELOCATION) ]; then cp -f ./logrotate.dansguardian $I$(LOGROTATELOCATION)dansguardian; fi
 
 uninstall:
